# Generated by Django 2.1.5 on 2019-02-09 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportAPI', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UILayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.IntegerField()),
                ('tsid', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='tsid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
