# Generated by Django 2.1.5 on 2019-02-09 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportAPI', '0004_auto_20190209_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=255)),
                ('association_table', models.CharField(max_length=255)),
                ('join_type', models.CharField(max_length=255)),
                ('table_column_name', models.CharField(max_length=255)),
                ('association_column_name', models.CharField(max_length=255)),
                ('tsid', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
