# Generated by Django 2.1.5 on 2019-02-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportAPI', '0005_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportAPI.Category'),
        ),
    ]
