# Generated by Django 2.1.5 on 2019-02-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportAPI', '0006_auto_20190209_0650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='Association',
        ),
    ]
